@@include('@@nodeRoot/../node_modules/datatables.net-buttons/js/dataTables.buttons.min.js')
@@include('@@nodeRoot/../node_modules/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')
@@include('@@nodeRoot/../node_modules/datatables.net-buttons/js/buttons.colVis.js')
@@include('@@nodeRoot/../node_modules/jszip/dist/jszip.min.js')
@@include('@@nodeRoot/../node_modules/pdfmake/build/pdfmake.min.js')
@@include('@@nodeRoot/../node_modules/pdfmake/build/vfs_fonts.js')
@@include('@@nodeRoot/../node_modules/datatables.net-buttons/js/buttons.html5.min.js')
@@include('@@nodeRoot/../node_modules/datatables.net-buttons/js/buttons.print.min.js')